name: Deploy Docs

on:
    workflow_run:
      workflows: ["Release"]  # Name of the first workflow
      types:
        - completed  # Can be 'requested', 'completed', or 'in_progress'
      branches:
        - main  # Only run on the main branch

jobs:
    deploy-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
                    
          - name: Set environment variables
            run: echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV
          
          - name: Set GitHub identity
            run: |
              git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
              git config --global user.name "${GITHUB_ACTOR}"
                
          - name: Prepare gh-pages
            run: |
              git fetch origin
              if ! git rev-parse --verify origin/gh-pages; then
                git checkout --orphan gh-pages
                git rm -rf .
                echo "Created new gh-pages branch."
              else
                git checkout gh-pages
              fi
              mkdir main
              git archive --format=tar main | tar -x -C main
          
          - run: chmod +x ./main/scripts/unix/*
                    
          - name: Generate docs
            run: |
              ./main/scripts/unix/copy-additional-files.sh
              cd main
              npm i
              npm run generate-docs
              cd ..
              ./main/scripts/unix/process-and-commit-docs.sh